
use nikehealthchecker;

DROP TABLE DQ_RULE_R33MC_CASE_RUN_HISTORY_TAB;
DROP TABLE DQ_RULE_R33MC_CASE_TAB;
DROP TABLE DQ_RULE_R21FC_CASE_RUN_HISTORY_TAB;
DROP TABLE DQ_RULE_R21FC_CASE_TAB;
DROP TABLE DQ_RULE_QS_CASE_RUN_HISTORY_TAB;
DROP TABLE DQ_RULE_QS_CASE_TAB;
DROP TABLE DQ_RULE_TC_CASE_RUN_HISTORY_TAB;
DROP TABLE DQ_RULE_TC_CASE_TAB;
DROP TABLE DQ_DB_CONNECTION_TAB;

DROP TABLE DQ_USER_ROLE_PERMISSION_MAPPING_TAB;
DROP TABLE DQ_USER_ROLE_PERMISSION_TAB;
DROP TABLE DQ_USER_ROLE_MAPPING_TAB;
DROP TABLE DQ_USER_ROLE_TAB;
DROP TABLE DQ_USER_PROFILE_TAB;
